### ISSUE TITLE
Remove Flavors

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#119]
They're a whole lot more hassle than they're worth.

```[tasklist]
## Tasks
- [x] Remove Flavor-dependent code in Dart files
- [x] Remove `dart_define.flavors` in pubspec
- [x] Move `flutter_launcher_icons.yaml` into pubspec
- [x] Remove `--flavor` in build invocations
- [x] Remove alternate entrypoint files (`main_*.dart`)
- [x] Remove `flavorDimensions` and `productFlavors` from `android/app/build.gradle`
- [ ] Update docs accordingly
```

_Supersedes_: #103
