### ISSUE TITLE
Login Screen

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#124]
```[tasklist]
### Tasks
- [x] Make a page with a button saying "Login with Google"
- [x] Add Google Auth
- [x] Navigate to `WrapperPage`
```
