### ISSUE TITLE
Minor, Misc

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#161]
### Why

I needed to write it down before I forgot.

### The Plan

```[tasklist]
## Tasks
- [x] Fix `package:io/ansi.dart` so it doesn't run in web #187
- [x] Cache, rather than artifact-ing, generated files in CI
- [x] Review freezed classes to ensure uniformity
- [x] Double-check that all `builders` are scoped to as few files as possible
- [ ] #188
- [x] Unify snackbars #187
- [x] Check GHA Security
```

**Comment by lishaduck** [comment]
e8702570cab7ec0d678602eb30a1c5f9fe733b43 is the last commit needed to finish these mini-projects.
