### ISSUE TITLE
Upgrade Consumers

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#170]
### Why

We need to follow best practices.

Related: #126.

### The Plan

```[tasklist]
## Tasks
- [ ] Use `ref.read` instead of `ref.watch` in event handlers.
- [ ] Scope consumers to the lowest possible level via the `Consumer` API.
- [ ] Also, pass data as parameters, not through extra consumers.
```

**Comment by lishaduck** [comment]
The `Consumer` API is far too annoying and thus will only be used on a case-by-case basis.

**Comment by lishaduck** [comment]
Ooops, forgot to close this.
