### ISSUE TITLE
More Tooling

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#177]
### Why

fzyzcjy's made some cool tools that look like they'll be useful.

### The Plan

```[tasklist]
## Tasks
- [ ] [`flutter_rust_bridge`](https://pub.dev/packages/flutter_rust_bridge) will be useful for cryptography stuff.
- [ ] [`flutter_convenient_test`](https://pub.dev/packages/convenient_test).
- [ ] [`flutter_smooth`](https://cjycode.com/flutter_smooth/) looks cool, but we'll want to wait until the engine patches are merged.
```

Also, if `flutter_rust_bridge` is used, or when we start using Appwrite functions, we'll need to re-visit #33.
