### ISSUE TITLE
Spell Checking

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#188]
### Why

We want the app to be properly spelt out.

### The Plan

```[tasklist]
## Tasks
- [x] Run [streetsidesoftware/cspell-action](https://github.com/marketplace/actions/cspell-action) over all of the code.
- [x] Fix Spelling Errors
- [ ] Run cspell over all repo content
- [ ] Run only changed files
```

**Comment by lishaduck** [comment]
a99d1d7823ba24a0b4465379e78da1f3fb56d265 & 68c6b48c75ce6a40c4f6c303013ac90835b80119 start work on this.

**Comment by lishaduck** [comment]
21c36e493512d35df5c86fcd768bc3fe9c4253f8 fixes this.

**Comment by lishaduck** [comment]
Realized this was done incompletely, so I've updated to todo list.
