### ISSUE TITLE
Support Anonymous Users

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#189]
### Why

You shouldn't need an account to use the GPA Calculator (#164).

### The Plan

```[tasklist]
## Tasks
- [x] Add a new button on the login page.
- [x] Wire the new button up.
- [x] Make any other changes needed to keep it type-checking.
- [x] Make any other UI changes needed to keep it looking nice.
```

**Comment by lishaduck** [comment]
Closed by #187.
