### ISSUE TITLE
Pin Dependencies

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#225]
### Why

With a lockfile, dependency ranges are mostly useless.

@PetalCat, do you want to do this? It should be as simple as a find-replace.

### The Plan

```[tasklist]
## Tasks
- [ ] Remove all of the carets
- [ ] Remove all of the tildas
- [ ] Check if the lockfile needs regenerating
- [ ] Check if dependency versions now need bumping
```
