### ISSUE TITLE
Scope Mocks

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#237]
### Why

Right now, all mocks are implicitly used by every test, which isn't [wet](https://arlobelshee.com/what-makes-a-good-test-suite/arlo-belshee/).

### The Plan

```[tasklist]
#### Tasks
- [x] Remove the implicit mocks
- [x] Make them explicit on a per-test basis
- [ ] Switch to [nullables](https://www.jamesshore.com/v2/projects/nullables/testing-without-mocks)?
```
