### ISSUE TITLE
Thin Dependencies

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#253]
### Why

We don't need them all!

### The Plan

```[tasklist]
#### Remove
- [x] `widgetbook`—It slows down codegen so much I haven't even considered finishing #126.
- [x] `google_fonts`—It's not useful without runtime fetching and with `flutter_gen`.
- [ ] `auto_route`—I think it'd be wise to use `go_router`, as it's official, and the reason we use `auto_route` is no more.
- [x] `dart_define`?—It's mostly unmaintained, and `dart-define-from-file` appears to be getting phased out with 3.16.
- [x] `very_good_workflows`— I think we should just vendor it, which is why I haven't merged #243.
- [ ] `very_good_coverage`—Can we use #34 for this?
- [x] `very_good_dictionaries`—I'm starting to run into some issues with it.
- [x] `nix`—We aren't using replit anymore, so we don't need nix anymore.
- [x] `tamasfe.even-better-toml`, `bbenoist.nix`, `foam.foam-vscode`, `tyriar.luna-paint`—We don't need these in `extensions.json` anymore.
- [x] Also, remove `python` label because we never actually use python for anything.
- [x] [Remove](https://sobolevn.me/2020/03/do-not-log) [log](d72c995aedd675118c491369274869b60e2cb2e5)[ging](https://github.com/PSDTools/app/pull/150) (Between [Kenton Varda](https://kentonshouse.com/singletons#TOC-What-about-debug-logging-) and Nikita Sobolev, I'm convinced.) (And we can remove the annoying `package:io` on web issue.)
- [x] `.devcontainer/`—Don't use it, don't need it.
- [ ] #263
- [x] Copilot for PRs
```

**Comment by lishaduck** [comment]
Another option from `dart_define`:  [How to Store API Keys in Flutter: --dart-define vs .env files](https://codewithandrea.com/articles/flutter-api-keys-dart-define-env-files/).

**Comment by lishaduck** [comment]
Removing `auto_route` will need to be on hold for a bit.
