### ISSUE TITLE
Fix Realtime on web

### ISSUE THREAD

**Issue by lishaduck** [PSDTools/app#271]
### Why

Apparently, Websockets are subject to CORS, thus we'll need to figure out a different way to handle them there. Realtime works on a mac. Sometimes. I should check that too.

### The Plan

```[tasklist]
#### Tasks
- [ ] Fix it for web.
- [ ] Check for other platforms still-working-ness
- [ ] Fix those (if necessary)
```
